{% set name = "xtensor-python" %}
{% set version = "0.2.0" %}
{% set sha256 = "195907c0f7788be3ab063947c56faf8a1d919bb085d3f67e1b9adbc92d2e3388" %} 

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/QuantStack/xtensor-python/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 1

requirements:
  run:
    - xtensor ==0.2.1
    - pybind11 ==1.8.1

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-python  # [unix]
    - test -f ${PREFIX}/include/xtensor-python/pyarray.hpp  # [unix]
    - if exist %PREFIX%\include\xtensor-python\pyarray.hpp (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python bindings for xtensor, the C++ tensor algebra library'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  doc_url: http://xtensor.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor-python

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
