{% set name = "xtensor-python" %}
{% set version = "0.12.0" %}
{% set sha256 = "2af7ca3b6e11155d62ce33bce3ff3d913c94ab98723646fafe0fd75a892e01d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/QuantStack/xtensor-python/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0

requirements:
  run:
    - xtensor >=0.10.2,<0.11
    - pybind11 >=2.1.0,<2.2

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-python  # [unix]
    - test -f ${PREFIX}/include/xtensor-python/pyarray.hpp  # [unix]
    - if exist %PREFIX%\include\xtensor-python\pyarray.hpp (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python bindings for xtensor, the C++ tensor algebra library'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  doc_url: http://xtensor.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor-python

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
