{% set name = "xtensor-python" %}
{% set version = "0.15.0" %}
{% set sha256 = "c7c25b4a453053f6692355b05ff70783e147963054af7a8ffe321eb0e7a31b61" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/QuantStack/xtensor-python/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - toolchain
    - cmake
    - xtl
    - xtensor
    - pybind11
    - numpy
  run:
    - xtl >=0.3.3,<0.4
    - xtensor >=0.13.1,<0.14
    - pybind11 >=2.1.0,<2.3
    - numpy

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-python  # [unix]
    - test -f ${PREFIX}/include/xtensor-python/pyarray.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-python/xtensor-pythonConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-python/xtensor-pythonConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xtensor-python\pyarray.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-pythonConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-pythonConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python bindings for xtensor, the C++ tensor algebra library'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  doc_url: http://xtensor.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor-python

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
