travis:
  secure:
    BINSTAR_TOKEN: kQAeMIkPFHicr4x6MTrgJb8kbg5CTm5sU/p9x3gLaR7rNHBW59oIN1YriQxxv37TIKJ5cpG2NyCE1KaMX6nOPPBDpaldQIovLJC/s9FqOubyCbevgS3aXgHU7Tqg5re2m6M3uaWLn/zdFp4Rm7KMfZwCBO1BxpuQSSnYAmRPvFattISgKrKy85mzYqzXqcMnpifuLWI8xdymt1+9yl9UwkYGxsH/6Oe8iWOLZEcgd7fBfyNFV8dyFJU32IxUZAE5KERf5wcqDFxxw7hLGEMsu68LnO1x8BYLbAoc95vFLlxhRRNhOrYmmbxBC/3Nw3PeAGLuuCDyjUXgf7znqYe3YDYbrQZgiPpavM11nXWszHPIhY6UwM/kQOD3RvOeOJk6T6LxjVzF2/8JXacxd99cnd8Ta4kAXzfF1wLrgJP4+LjAjduvA8wcFq9vESQlu0xTREk+qnFHiK87ndYPle0pzZjC/nPQc5ySZf6pxnJ4KNqeyNsaEgeOY51nxUpNYM0N8/P9lf2iCG0LLQaoiD5PX7S9Fvv9s8JNuuHZ9pD6WblwC8s8dTTR1HpwQnZ8dF3y4SjuMpURecTwMgIa40ijTBW0NOYim8vFeAlebR9fiZNYDwLacH7owy/Vljp5AkN0ZQ38KNrP47G2oF/symAIdPJrLW7KmYUCT+vLPzKyfck=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
